name: Node.js CI to build roleInfo.js

on:
  push:
    branches: [main]
    paths:
    - index.html
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - run: npm i linkedom
      - run: node ./common/script/buildRoleInfo.js
      - run: git add ./common/script/roleInfo.js
      - run: git commit -m'chore: update roleInfo.js'
      - run: git push
